export { UserProfile } from "./Profile/User";
export { PersonalHealthRecords } from "./PersonalHealthRecords";
export { DoctorRecommendation } from "./DoctorRecommendation";
export { Appointments } from "./Appointments";
export { BookAppointment } from "./BookAppointment";
export { SignupUser } from "./Signup/SignupUser";
export { DashboardDoctor } from "./Dashboard/DashboardDoctor";
export { LoginHospital } from "./Login/LoginHospital";
export { LoginDoctor } from "./Login/LoginDoctor";
export { LoginUser } from "./Login/LoginUser";
export { DashboardUser } from "./Dashboard/DashboardUser";
export { LandingPage } from './LandingPage/LandingPage'
